// Generated by bridgerton. Prototype: Swift 6.2+, main-actor confinement.
import Foundation
import BridgeFFI

@MainActor private enum BridgeInterface {
    static let checked: Void = {
    let expected: [UInt8] = [@bridge_interface_bytes@]
    precondition(expected.withUnsafeBufferPointer {
        bridgerton_abi_v1_matches($0.baseAddress, $0.count) != 0
    }, "bridgerton: Swift bindings do not match the Rust library; regenerate the bindings")
    }()
}

public struct BridgeError: Swift.Error, CustomStringConvertible {
    public let description: String
}

// Results contain an owned buffer. Every path consumes it exactly once.
@MainActor private func bridgeText(_ result: BridgeResult) -> String {
    guard let data = result.data.data else { return "" }
    return String(decoding: UnsafeBufferPointer(start: data, count: result.data.len), as: UTF8.self)
}

@MainActor private func bridgeCheck(_ result: BridgeResult) throws {
    if result.status > 1 { throw BridgeError(description: bridgeText(result)) }
}

@MainActor private func bridgeNumber(_ result: BridgeResult) throws -> UInt32 {
    defer { bridgerton_buffer_free(result.data) }
    try bridgeCheck(result)
    return result.value
}

@MainActor private func bridgeString(_ result: BridgeResult) throws -> String {
    defer { bridgerton_buffer_free(result.data) }
    try bridgeCheck(result)
    return bridgeText(result)
}

@MainActor private func bridgeHandle(_ result: BridgeResult) throws -> UnsafeRawPointer {
    defer { bridgerton_buffer_free(result.data) }
    try bridgeCheck(result)
    guard let handle = result.handle else { throw BridgeError(description: "missing Rust handle") }
    return handle
}

// Each generated type declares its return transport once.
internal protocol BridgeReturn {
    @MainActor static func bridgeReceive(_ result: BridgeResult, context: inout BridgeReturnContext) throws -> Self
    @MainActor static func bridgeReceiveArray(_ result: BridgeResult, context: inout BridgeReturnContext) throws -> [Self]
    @MainActor static func bridgeReceiveOptional(_ result: BridgeResult, context: inout BridgeReturnContext) throws -> Self?
}
internal protocol BridgeObject: AnyObject, BridgeReturn {
    @MainActor init(bridgeHandle: UnsafeRawPointer)
}
extension BridgeObject {
    @MainActor internal static func bridgeReceive(_ result: BridgeResult, context: inout BridgeReturnContext) throws -> Self {
        Self(bridgeHandle: try bridgeHandle(result))
    }
}
@MainActor private func bridgeReturn<T: BridgeReturn>(_ result: BridgeResult) throws -> T {
    var context = BridgeReturnContext()
    return try T.bridgeReceive(result, context: &context)
}

// One budget covers the complete return tree, including nested object containers.
internal struct BridgeReturnContext {
    var remainingBytes = bridgeMaxBytes
    var remainingItems = bridgeMaxItems
    var depth = 0
}
extension BridgeReturn {
    @MainActor internal static func bridgeReceiveArray(_ result: BridgeResult, context: inout BridgeReturnContext) throws -> [Self] {
        try bridgeSequence(result, context: &context, optional: false)
    }
    @MainActor internal static func bridgeReceiveOptional(_ result: BridgeResult, context: inout BridgeReturnContext) throws -> Self? {
        let values: [Self] = try bridgeSequence(result, context: &context, optional: true)
        return values.first
    }
}
extension Array: BridgeReturn where Element: BridgeReturn {
    @MainActor internal static func bridgeReceive(_ result: BridgeResult, context: inout BridgeReturnContext) throws -> Self {
        try Element.bridgeReceiveArray(result, context: &context)
    }
}
extension Optional: BridgeReturn where Wrapped: BridgeReturn {
    @MainActor internal static func bridgeReceive(_ result: BridgeResult, context: inout BridgeReturnContext) throws -> Self {
        try Wrapped.bridgeReceiveOptional(result, context: &context)
    }
}
@MainActor private func bridgeSequence<T: BridgeReturn>(_ result: BridgeResult, context: inout BridgeReturnContext, optional: Bool) throws -> [T] {
    let handle = try bridgeHandle(result)
    defer { _ = try! bridgeNumber(bridgerton_sequence_free(handle)) }
    let count = Int(result.value)
    guard count <= context.remainingItems, !optional || count <= 1 else { throw BridgeError(description: "invalid return sequence length") }
    guard context.depth < bridgeMaxDepth else { throw BridgeError(description: "value exceeds nesting limit") }
    context.remainingItems -= count
    context.depth += 1
    defer { context.depth -= 1 }
    var values: [T] = []
    values.reserveCapacity(count)
    for _ in 0..<count {
        values.append(try T.bridgeReceive(bridgerton_sequence_next(handle), context: &context))
    }
    return values
}

// The callback owns a lazy argument sequence. Unclaimed arguments are dropped
// when the sequence is freed; decoded objects can outlive the callback.
@MainActor private final class BridgeCallbackBox {
    let body: @MainActor (UnsafeRawPointer, Int) throws -> Void
    init(_ body: @escaping @MainActor (UnsafeRawPointer, Int) throws -> Void) { self.body = body }
    isolated deinit {}
}

private func bridgeInvoke(_ context: Int, _ value: BridgeResult) -> UInt8 {
    precondition(value.status == 0 && value.data.data == nil && value.handle != nil)
    let handle = Int(bitPattern: value.handle!)
    let count = Int(value.value)
    return MainActor.assumeIsolated {
        do {
            try Unmanaged<BridgeCallbackBox>.fromOpaque(UnsafeRawPointer(bitPattern: context)!).takeUnretainedValue().body(UnsafeRawPointer(bitPattern: handle)!, count)
            return 1
        } catch { return 0 }
    }
}
private func bridgeRelease(_ context: Int) {
    MainActor.assumeIsolated {
        Unmanaged<BridgeCallbackBox>.fromOpaque(UnsafeRawPointer(bitPattern: context)!).release()
    }
}
@MainActor private func bridgeCallbackArguments(_ expected: Int, _ body: @escaping @MainActor (UnsafeRawPointer, inout BridgeReturnContext) throws -> Void) -> BridgeHostCallback {
    let box = BridgeCallbackBox { handle, count in
        defer { _ = try! bridgeNumber(bridgerton_sequence_free(handle)) }
        precondition(count == expected)
        var context = BridgeReturnContext()
        context.remainingItems -= count
        try body(handle, &context)
    }
    let context = Unmanaged.passRetained(box).toOpaque()
    return BridgeHostCallback(context: Int(bitPattern: context), invoke: bridgeInvoke, release: bridgeRelease)
}
@MainActor private func bridgeCallback0(_ body: @escaping @MainActor () -> Void) -> BridgeHostCallback {
    bridgeCallbackArguments(0) { _, _ in body() }
}
@MainActor private func bridgeCallback1<T: BridgeReturn>(_ body: @escaping @MainActor (T) -> Void) -> BridgeHostCallback {
    bridgeCallbackArguments(1) { handle, context in
        let value = try T.bridgeReceive(bridgerton_sequence_next(handle), context: &context)
        body(value)
    }
}
@MainActor private func bridgeCallback2<A: BridgeReturn, B: BridgeReturn>(_ body: @escaping @MainActor (A, B) -> Void) -> BridgeHostCallback {
    bridgeCallbackArguments(2) { handle, context in
        let first = try A.bridgeReceive(bridgerton_sequence_next(handle), context: &context)
        let second = try B.bridgeReceive(bridgerton_sequence_next(handle), context: &context)
        body(first, second)
    }
}
@MainActor private func bridgeCallback3<A: BridgeReturn, B: BridgeReturn, C: BridgeReturn>(_ body: @escaping @MainActor (A, B, C) -> Void) -> BridgeHostCallback {
    bridgeCallbackArguments(3) { handle, context in
        let first = try A.bridgeReceive(bridgerton_sequence_next(handle), context: &context)
        let second = try B.bridgeReceive(bridgerton_sequence_next(handle), context: &context)
        let third = try C.bridgeReceive(bridgerton_sequence_next(handle), context: &context)
        body(first, second, third)
    }
}

@MainActor private final class BridgeWaiter {
    var continuation: CheckedContinuation<Void, Never>?
    var signaled = false
    func wake() {
        if let continuation {
            self.continuation = nil
            continuation.resume()
        } else { signaled = true }
    }
    func wait() async {
        if signaled { signaled = false; return }
        await withCheckedContinuation { continuation = $0 }
    }
}

@MainActor private enum BridgeWaiters {
    static var nextID: UInt64 = 0
    static var items: [UInt64: BridgeWaiter] = [:]
    static func register(_ waiter: BridgeWaiter) -> UInt64 {
        nextID += 1 // Overflow traps rather than reusing an ID for a late notification.
        items[nextID] = waiter
        return nextID
    }
}

// May run on any thread. Only a number crosses; no Rust object/future pointer is captured.
private func bridgeWake(_ id: UInt64) {
    Task { @MainActor in BridgeWaiters.items[id]?.wake() }
}

@MainActor private func bridgeAwait(_ handle: UnsafeRawPointer, cancellable: Bool, abortControllers: [AbortController]) async throws -> BridgeResult {
    let waiter = BridgeWaiter()
    let id = BridgeWaiters.register(waiter)
    defer {
        BridgeWaiters.items.removeValue(forKey: id)
        let result = bridgerton_task_free(handle)
        _ = try! bridgeNumber(result)
    }
    return try await withTaskCancellationHandler {
        while true {
            // A nonthrowing Rust future must finish to supply its result.
            if Task.isCancelled {
                for controller in abortControllers { controller.abort() }
                if cancellable { try Task.checkCancellation() }
            }
            let result = bridgerton_task_poll(handle, bridgeWake, id)
            if result.status != 1 { return result }
            bridgerton_buffer_free(result.data)
            await waiter.wait()
        }
    } onCancel: {
        // Cancellation handlers can run off-actor. Wake the driver; it owns cancellation cleanup.
        bridgeWake(id)
    }
}

// Typed errors use the same bounded value codec; transport failures remain BridgeError.
@MainActor private func bridgeTypedResult<E: BridgeValue & Swift.Error>(
    _ result: BridgeResult, as type: E.Type
) throws -> BridgeResult {
    guard result.status == 3 else { return result }
    var payload = result
    payload.status = 0
    let error: E = try bridgeValue(payload) // Consumes the buffer even if decoding fails.
    throw error
}
