[package]
name = "stroke-order"
version = "0.1.0"
edition = "2024"

[dependencies]
language-utils = { path = "../../language-utils" }
anyhow = "1"
bridgerton.workspace = true
rkyv.workspace = true
serde.workspace = true
serde_json.workspace = true
zip.workspace = true
rustc-hash = "2.1"
roxmltree = "0.21.1"
svgtypes = "0.16.1"
unicode-normalization.workspace = true

[dev-dependencies]
reqwest.workspace = true
tokio.workspace = true
