[package]
name = "weapon"
version = "0.1.1"
edition = "2024"
description = "Cross-device sync engine"
license = "MIT"
authors = ["Andre Popovitch <andre@popovit.ch>"]

[[bin]]
name = "weapon-scope"
path = "src/bin/weapon-scope.rs"

[dependencies]
web-time.workspace = true
bridgerton.workspace = true
chrono = { workspace = true, features = ["serde"] }
im.workspace = true
serde.workspace = true
log.workspace = true
serde_json.workspace = true

fetch-happen = { workspace = true, optional = true }
opfs = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
slotmap = { workspace = true }
weblocks = { workspace = true }

[features]
supabase = ["dep:fetch-happen", "dep:thiserror"]
opfs = [
    "dep:opfs",
    "dep:futures",
    "dep:thiserror",
]
