[package]
name = "ai-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13", default-features = false, features = [
    "json",
    "multipart",
    "rustls",
] }
base64 = "0.22"
axum = "0.8.9"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
tysm.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
tower = { version = "0.5" }
tower-http = { version = "0.6", features = [
    "cors",
    "compression-br",
    "compression-gzip",
    "compression-deflate",
    "compression-zstd",
] }
jsonwebtoken = { version = "10.4", features = ["rust_crypto"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
dotenvy = "0.15.7"
uuid = { version = "1.23", features = ["serde", "v4"] }
language-utils = { path = "../language-utils" }
autograde-core = { path = "../libraries/autograde-core" }
g2p.workspace = true
tsify.workspace = true
wasm-bindgen.workspace = true
postgrest = "1.6"
resend-rs = "0.25"
google-tts = { path = "../libraries/google-tts" }
unicode-normalization.workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
