[package]
name = "phoneme-verify"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
half = "2.7.1"
flate2 = "1.1.9"
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
xxhash-rust = { workspace = true }
osmo = { workspace = true }
language-utils = { path = "../../language-utils" }
google-tts = { path = "../google-tts" }
g2p = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
