[package]
name = "phoneme-verify"
version = "0.1.0"
edition = "2024"

[dependencies]
audio-codec = { path = "../audio-codec" }
anyhow = "1.0"
base64 = "0.22"
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
xxhash-rust = { workspace = true }
osmo = { workspace = true }
language-utils = { path = "../../language-utils" }
google-speech = { path = "../google-speech" }
g2p = { workspace = true }
lexide = { workspace = true }

[dev-dependencies]
half = "2.7.1"
flate2 = "1.1.9"
tempfile = { workspace = true }
