[package]
name = "subtitle-corpus"
version = "0.1.0"
edition = "2021"

[dependencies]
g2p = { workspace = true }
whisper = { path = "../whisper" }
anyhow = "1.0"
dotenvy = "0.15.7"
clap = { version = "4", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["png"] }
serde = { workspace = true }
serde_json = { workspace = true }
tysm = { workspace = true }
schemars = { workspace = true }
base64 = "0.22"
tokio = { workspace = true }
futures = { workspace = true }
movie-subtitles = { path = "../movie-subtitles" }
reqwest = { workspace = true }
language-utils = { path = "../../language-utils" }
earshot = "1.1"
matroska-demuxer = "0.8.1"
flate2 = "1.1.9"
osmo = { workspace = true }
xxhash-rust = { workspace = true }
tempfile = { workspace = true }
google-speech = { path = "../google-speech" }
phoneme-verify = { path = "../phoneme-verify" }
opensubtitles-downloader = { path = "../opensubtitles-downloader" }
sha2 = "0.10"
unicode-normalization = { workspace = true }
object_store = { version = "0.14.2", features = ["aws"] }
md-5 = "0.11.0"
movie-metadata = { path = "../movie-metadata" }
rayon = "1.12.0"
