[package]
name = "google-tts"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = "1"
log = { workspace = true }
tokio = { workspace = true, features = ["time"] }
base64 = "0.22"
minimp3 = "0.6"
ogg = "0.9"
opus = "0.3"
hound = "3.5.1"
