use crate::{Result, command, root, run_capture, text};
use clap::Args as ClapArgs;
use serde_json::Value;
use std::{fs, io::Write};

pub const BUNDLE: &str = "town.yap.ios";

#[derive(ClapArgs, Default)]
pub struct Args {
    /// Build release libraries and app (the default).
    #[arg(long, conflicts_with = "debug")]
    pub release: bool,
    /// Build debug libraries and app.
    #[arg(long, conflicts_with = "archive")]
    pub debug: bool,
    /// Install and launch on UUID, or the single booted simulator if omitted.
    #[arg(long, num_args = 0..=1, default_missing_value = "booted", value_name = "UUID", group = "mode")]
    pub simulator: Option<String>,
    /// Build the simulator app without installing or launching.
    #[arg(long, group = "mode")]
    pub simulator_build_only: bool,
    /// Install and launch on a hardware UDID or CoreDevice UUID.
    #[arg(long, value_name = "UDID", group = "mode")]
    pub device: Option<String>,
    /// Archive and export for App Store Connect; never upload.
    #[arg(long, group = "mode")]
    pub archive: bool,
}

fn artifacts(stdout: &str, stderr: &str) -> Result<(String, Vec<String>)> {
    let mut archives = Vec::new();
    for line in stdout.lines().filter(|line| line.starts_with('{')) {
        let artifact: Value = serde_json::from_str(line)?;
        if artifact["reason"] == "compiler-artifact" && artifact["target"]["name"] == "yap_ios_host"
        {
            for name in artifact["filenames"]
                .as_array()
                .ok_or("missing artifact filenames")?
            {
                let name = name.as_str().ok_or("invalid artifact filename")?;
                if name.ends_with(".a") {
                    archives.push(name.to_owned());
                }
            }
        }
    }
    if archives.len() != 1 {
        return Err(format!(
            "expected exactly one yap_ios_host static archive, found {archives:?}"
        )
        .into());
    }
    let native: Vec<_> = stderr
        .lines()
        .filter_map(|line| line.strip_prefix("note: native-static-libs: "))
        .collect();
    if native.len() != 1 {
        return Err(format!(
            "expected exactly one native-static-libs note, found {}",
            native.len()
        )
        .into());
    }
    Ok((
        archives.remove(0),
        native[0].split_whitespace().map(str::to_owned).collect(),
    ))
}

fn build_rust(target: &str, release: bool) -> Result<(String, Vec<String>)> {
    let mut cmd = command("cargo");
    cmd.args(["rustc", "-p", "yap-ios-host", "--lib", "--locked"]);
    if release {
        cmd.arg("--release");
    }
    cmd.args([
        "--target",
        target,
        "--message-format=json-render-diagnostics",
        "--",
        "--print=native-static-libs",
    ])
    .env("IPHONEOS_DEPLOYMENT_TARGET", "18.0")
    .env("CARGO_TERM_COLOR", "never");
    let built = run_capture(&mut cmd)?;
    std::io::stderr().write_all(&built.stderr)?;
    artifacts(
        std::str::from_utf8(&built.stdout)?,
        std::str::from_utf8(&built.stderr)?,
    )
}

pub fn run(args: Args) -> Result<()> {
    if args.archive && args.debug {
        return Err("--archive requires --release".into());
    }
    let release = !args.debug;
    let here = root().join("yap-ios");
    let generated = here.join("Generated");
    fs::create_dir_all(&generated)?;
    let mut lines = vec![
        "// Generated by cargo xtask ios; do not edit.".to_owned(),
        "SENTRY_DSN =".into(),
        "#include? \"../Local.xcconfig\"".into(),
    ];
    for (sdk, target) in [
        ("iphoneos", "aarch64-apple-ios"),
        ("iphonesimulator", "aarch64-apple-ios-sim"),
    ] {
        let (archive, libraries) = build_rust(target, release)?;
        let flags = std::iter::once(format!("-Wl,-force_load,{archive}"))
            .chain(libraries)
            .map(|flag| format!("\"{flag}\""))
            .collect::<Vec<_>>()
            .join(" ");
        lines.push(format!("OTHER_LDFLAGS[sdk={sdk}*] = $(inherited) {flags}"));
    }
    let mut bridge = command("cargo");
    bridge.args(["bridgerton", "swift", "--package", "yap-ios-host"]);
    if release {
        bridge.arg("--release");
    }
    crate::run(
        bridge
            .arg("--locked")
            .arg("--out-dir")
            .arg(generated.join("Bindings")),
    )?;
    fs::write(generated.join("Link.xcconfig"), lines.join("\n") + "\n")?;
    crate::run(
        command("xcodegen")
            .args(["generate", "--spec"])
            .arg(here.join("project.yml")),
    )?;
    let derived = here.join("DerivedData");
    if args.archive {
        let archive = derived.join("Yap.xcarchive");
        crate::run(
            command("xcodebuild")
                .args(["archive", "-project"])
                .arg(here.join("Yap.xcodeproj"))
                .args([
                    "-scheme",
                    "Yap",
                    "-configuration",
                    "Release",
                    "-destination",
                    "generic/platform=iOS",
                    "-archivePath",
                ])
                .arg(&archive)
                .arg("-derivedDataPath")
                .arg(&derived)
                .arg("-allowProvisioningUpdates"),
        )?;
        let options = generated.join("ExportOptions.plist");
        fs::write(&options, EXPORT_OPTIONS)?;
        crate::run(
            command("xcodebuild")
                .args(["-exportArchive", "-archivePath"])
                .arg(archive)
                .arg("-exportOptionsPlist")
                .arg(options)
                .arg("-exportPath")
                .arg(derived.join("export"))
                .arg("-allowProvisioningUpdates"),
        )?;
        return Ok(());
    }
    if args.simulator.is_none() && !args.simulator_build_only && args.device.is_none() {
        return Ok(());
    }
    let mut simulator = args.simulator;
    if simulator.as_deref() == Some("booted") {
        let devices: Value = serde_json::from_str(&text(
            command("xcrun").args(["simctl", "list", "devices", "booted", "--json"]),
        )?)?;
        simulator = Some(booted_simulator(&devices)?);
    }
    let destination = if let Some(device) = &args.device {
        let directory = tempfile::Builder::new().prefix("yap-device-").tempdir()?;
        let details = directory.path().join("details.json");
        crate::run(
            command("xcrun")
                .args([
                    "devicectl",
                    "device",
                    "info",
                    "details",
                    "--device",
                    device,
                    "--json-output",
                ])
                .arg(&details)
                .stdout(std::process::Stdio::null()),
        )?;
        let details: Value = serde_json::from_slice(&fs::read(details)?)?;
        format!(
            "id={}",
            details["result"]["hardwareProperties"]["udid"]
                .as_str()
                .ok_or("missing hardware UDID")?
        )
    } else if let Some(simulator) = &simulator {
        format!("platform=iOS Simulator,id={simulator}")
    } else {
        "generic/platform=iOS Simulator".into()
    };
    let configuration = if release { "Release" } else { "Debug" };
    let mut build = command("xcodebuild");
    build
        // Warnings and errors only, so a failure ends with its Swift errors, not build noise.
        .args(["build", "-quiet", "-project"])
        .arg(here.join("Yap.xcodeproj"))
        .args([
            "-scheme",
            "Yap",
            "-configuration",
            configuration,
            "-destination",
            &destination,
            "-derivedDataPath",
        ])
        .arg(&derived);
    if args.device.is_some() {
        build.args([
            "-allowProvisioningUpdates",
            "-allowProvisioningDeviceRegistration",
        ]);
    } else {
        build.args(["CODE_SIGNING_ALLOWED=YES", "CODE_SIGN_IDENTITY=-"]);
    }
    crate::run(&mut build)?;
    let sdk = if args.device.is_some() {
        "iphoneos"
    } else {
        "iphonesimulator"
    };
    let app = derived.join(format!("Build/Products/{configuration}-{sdk}/Yap.app"));
    if let Some(device) = args.device {
        crate::run(
            command("xcrun")
                .args(["devicectl", "device", "install", "app", "--device", &device])
                .arg(app),
        )?;
        crate::run(command("xcrun").args([
            "devicectl",
            "device",
            "process",
            "launch",
            "--device",
            &device,
            "--terminate-existing",
            BUNDLE,
        ]))?;
    } else if let Some(simulator) = simulator {
        crate::run(
            command("xcrun")
                .args(["simctl", "install", &simulator])
                .arg(app),
        )?;
        crate::run(command("xcrun").args([
            "simctl",
            "launch",
            "--terminate-running-process",
            &simulator,
            BUNDLE,
        ]))?;
    }
    Ok(())
}

fn booted_simulator(devices: &Value) -> Result<String> {
    let mut booted = Vec::new();
    for group in devices["devices"]
        .as_object()
        .ok_or("missing simulator devices")?
        .values()
    {
        for device in group.as_array().ok_or("invalid simulator group")? {
            if device["state"] == "Booted" {
                booted.push(
                    device["udid"]
                        .as_str()
                        .ok_or("missing simulator UDID")?
                        .to_owned(),
                );
            }
        }
    }
    if booted.len() != 1 {
        return Err(
            "Specify --simulator UUID when there is not exactly one booted simulator".into(),
        );
    }
    Ok(booted.remove(0))
}

const EXPORT_OPTIONS: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>method</key><string>app-store-connect</string>
<key>teamID</key><string>AF2CJ3G3ZU</string>
<key>uploadSymbols</key><true/>
<key>destination</key><string>export</string>
<key>signingStyle</key><string>automatic</string>
</dict></plist>
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn cargo_artifacts_and_native_flags() {
        let stdout = "not json\n{\"reason\":\"compiler-artifact\",\"target\":{\"name\":\"yap_ios_host\"},\"filenames\":[\"/tmp/with space/lib.a\",\"/tmp/lib.dylib\"]}\n";
        let stderr =
            "warning: example\nnote: native-static-libs: -lSystem -framework CoreFoundation\n";
        assert_eq!(
            artifacts(stdout, stderr).unwrap(),
            (
                "/tmp/with space/lib.a".into(),
                vec![
                    "-lSystem".into(),
                    "-framework".into(),
                    "CoreFoundation".into()
                ]
            )
        );
        assert!(artifacts(stdout, "").is_err());
        assert!(artifacts(&format!("{stdout}{stdout}"), stderr).is_err());
    }

    #[test]
    fn exactly_one_booted_simulator() {
        assert_eq!(booted_simulator(&json!({"devices":{"ios":[{"state":"Booted","udid":"abc"},{"state":"Shutdown","udid":"def"}]}})).unwrap(), "abc");
        assert!(booted_simulator(&json!({"devices":{}})).is_err());
        assert!(booted_simulator(&json!({"devices":{"ios":[{"state":"Booted","udid":"abc"},{"state":"Booted","udid":"def"}]}})).is_err());
    }
}
