//! Generate both host shaders from one WGSL source. No host contains shader math.
use crate::{Result, root};
use naga::{
    ShaderStage,
    back::{glsl, msl},
    valid::{Capabilities, ValidationFlags, Validator},
};
use std::fs;

fn generate() -> Result<[(String, String); 2]> {
    let source = fs::read_to_string(root().join("shaders/background.wgsl"))?;
    let module = naga::front::wgsl::parse_str(&source).map_err(|e| e.emit_to_string(&source))?;
    let info = Validator::new(ValidationFlags::all(), Capabilities::empty()).validate(&module)?;
    // This is the std140 layout packed by the web worker. Check it against Naga's
    // parsed layout, so changes cannot silently desynchronize the two hosts.
    let (_, params) = module
        .types
        .iter()
        .find(|(_, t)| t.name.as_deref() == Some("Params"))
        .ok_or("missing Params")?;
    let naga::TypeInner::Struct { members, span } = &params.inner else {
        return Err("Params is not a struct".into());
    };
    assert_eq!(*span, 176, "update worker uniform packing");
    assert_eq!(
        members.iter().map(|m| m.offset).collect::<Vec<_>>(),
        [0, 8, 16, 24, 28, 32, 48],
        "update worker uniform packing"
    );
    let options = glsl::Options {
        version: glsl::Version::Embedded {
            version: 300,
            is_webgl: true,
        },
        // UV comes from the vertex varying, already bottom-left. No builtin
        // position or coordinate-space adjustment is involved.
        writer_flags: glsl::WriterFlags::empty(),
        ..Default::default()
    };
    let pipeline = glsl::PipelineOptions {
        shader_stage: ShaderStage::Fragment,
        entry_point: "fragment".into(),
        multiview: None,
    };
    let mut fragment = String::new();
    let reflection = glsl::Writer::new(
        &mut fragment,
        &module,
        &info,
        &options,
        &pipeline,
        Default::default(),
    )?
    .write()?;
    let uniform = module
        .global_variables
        .iter()
        .find(|(_, v)| v.name.as_deref() == Some("params"))
        .ok_or("missing uniform")?
        .0;
    println!("GLSL uniform: {:?}", reflection.uniforms.get(&uniform));

    // MSL needs only the pure functions. Remove the web entry and its uniform;
    // Naga still emits all ordinary functions, including background.
    let mut metal_module = module.clone();
    metal_module.entry_points.clear();
    metal_module.global_variables.clear();
    let metal_info =
        Validator::new(ValidationFlags::all(), Capabilities::empty()).validate(&metal_module)?;
    let (mut metal, _) = msl::write_string(
        &metal_module,
        &metal_info,
        &msl::Options {
            lang_version: (2, 4),
            fake_missing_bindings: false,
            ..Default::default()
        },
        &msl::PipelineOptions::default(),
    )?;
    // Naga's function name map is private. Discover the emitted helper's name
    // from its unique definition, not an assumed suffix; fail on ambiguity.
    let helpers: Vec<_> = metal
        .lines()
        .filter_map(|l| {
            l.trim()
                .strip_prefix("metal::float3 ")
                .and_then(|l| l.strip_suffix('('))
        })
        .filter(|name| name.starts_with("background"))
        .collect();
    let [helper] = helpers.as_slice() else {
        return Err("cannot uniquely locate generated background helper".into());
    };
    let helper = helper.to_string();
    if !metal.contains("struct Params {") {
        return Err("generated Params name changed".into());
    }
    if !metal.contains("metal::float4 inner[8];") {
        return Err("generated palette array layout changed".into());
    }
    println!("MSL helper: {helper}");
    metal.push_str(&format!(
        r#"
// SwiftUI supplies top-left point coordinates and a packed float-array palette.
// All calculations remain float until the final SwiftUI half4 return.
using namespace metal;
[[ stitchable ]] half4 yapBackground(float2 position, half4 currentColor,
    float2 size, float time, float2 mouse, float isDark, float oled, float numBands,
    device const float* colors, int colorCount) {{
    Params p = {{}};
    p.time = time;
    p.resolution = size;
    p.mouse = mouse;
    p.is_dark = isDark;
    p.oled = oled;
    p.num_bands = numBands;
    for (int i = 0; i < min(8, min(int(numBands), colorCount / 3)); ++i) {{
        p.colors.inner[i] = float4(colors[i * 3], colors[i * 3 + 1], colors[i * 3 + 2], 0.0);
    }}
    float2 uv = float2(position.x / size.x, 1.0 - position.y / size.y);
    return half4(half3({helper}(uv, p)), 1.0h);
}}
"#
    ));
    let header =
        "// Generated by `cargo xtask shaders` from shaders/background.wgsl. Do not edit.\n";
    // GLSL requires #version first.
    let (version, body) = fragment.split_once('\n').ok_or("missing GLSL version")?;
    Ok([
        (
            "yap-frontend/src/workers/background.generated.frag".into(),
            format!("{version}\n{header}{body}"),
        ),
        (
            "yap-ios/Sources/Design/Background.generated.metal".into(),
            format!("{header}{metal}"),
        ),
    ])
}

pub fn run() -> Result<()> {
    for (path, content) in generate()? {
        fs::write(root().join(path), content)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    #[test]
    fn generated_shaders_are_current() {
        for (path, expected) in super::generate().unwrap() {
            let actual = std::fs::read_to_string(crate::root().join(&path)).unwrap_or_default();
            assert_eq!(
                actual, expected,
                "{path} is stale; run `cargo xtask shaders`"
            );
        }
    }
}
