// Generated by `cargo xtask shaders` from shaders/background.wgsl. Do not edit.
// language: metal2.4
#include <metal_stdlib>
#include <simd/simd.h>

using metal::uint;

struct type_3 {
    metal::float4 inner[8];
};
struct Params {
    float time;
    char _pad1[4];
    metal::float2 resolution;
    metal::float2 mouse;
    float is_dark;
    float oled;
    float num_bands;
    char _pad6[12];
    type_3 colors;
};
struct type_6 {
    float inner[4];
};
struct type_8 {
    metal::float2 inner[6];
};
struct type_9 {
    float inner[6];
};

float blob(
    metal::float2 uv,
    metal::float2 center,
    float radius
) {
    float d = {};
    float t = {};
    d = metal::distance(uv, center);
    float _e7 = d;
    t = 1.0 - metal::smoothstep(0.0, radius * 2.0, _e7);
    float _e13 = t;
    float _e14 = t;
    return _e13 * _e14;
}

float sharedWave(
    float x,
    float t_1
) {
    return 0.04 * metal::sin((x * 4.8) - (t_1 * 0.08));
}

float layerHeight(
    float x_1,
    float baseY,
    float amp,
    float freq,
    float phase
) {
    float h = {};
    h = metal::sin((x_1 * freq) + phase) + (0.4 * metal::sin((((x_1 * freq) * 2.17) + (phase * 1.7)) + 1.3));
    float _e21 = h;
    return baseY + ((amp * _e21) / 1.4);
}

metal::float2 toAspect(
    metal::float2 p,
    float aspect
) {
    return (aspect > 1.0) ? metal::float2(p.x * aspect, p.y) : metal::float2(p.x, p.y / aspect);
}

float hash21_(
    metal::float2 point
) {
    metal::float2 p_1 = {};
    p_1 = metal::fract(point * metal::float2(443.897, 441.423));
    metal::float2 _e7 = p_1;
    metal::float2 _e8 = p_1;
    metal::float2 _e9 = p_1;
    p_1 = _e7 + metal::float2(metal::dot(_e8, _e9 + metal::float2(19.19)));
    float _e17 = p_1.x;
    float _e19 = p_1.y;
    return metal::fract(_e17 * _e19);
}

float valueNoise(
    metal::float2 p_2
) {
    metal::float2 i = {};
    metal::float2 f = {};
    float a = {};
    float b = {};
    float c = {};
    float d_1 = {};
    i = metal::floor(p_2);
    f = metal::fract(p_2);
    metal::float2 _e5 = f;
    metal::float2 _e6 = f;
    metal::float2 _e10 = f;
    f = (_e5 * _e6) * (metal::float2(3.0) - (2.0 * _e10));
    metal::float2 _e15 = i;
    float _e16 = hash21_(_e15);
    a = _e16;
    metal::float2 _e18 = i;
    float _e23 = hash21_(_e18 + metal::float2(1.0, 0.0));
    b = _e23;
    metal::float2 _e25 = i;
    float _e30 = hash21_(_e25 + metal::float2(0.0, 1.0));
    c = _e30;
    metal::float2 _e32 = i;
    float _e37 = hash21_(_e32 + metal::float2(1.0, 1.0));
    d_1 = _e37;
    float _e39 = a;
    float _e40 = b;
    float _e42 = f.x;
    float _e44 = c;
    float _e45 = d_1;
    float _e47 = f.x;
    float _e50 = f.y;
    return metal::mix(metal::mix(_e39, _e40, _e42), metal::mix(_e44, _e45, _e47), _e50);
}

float fbm(
    metal::float2 point_1
) {
    metal::float2 p_3 = {};
    float v = 0.0;
    float a_1 = 0.5;
    int i_1 = 0;
    p_3 = point_1;
    uint2 loop_bound = uint2(4294967295u);
    bool loop_init = true;
    while(true) {
        if (metal::all(loop_bound == uint2(0u))) { break; }
        loop_bound -= uint2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
            int _e23 = i_1;
            i_1 = as_type<int>(as_type<uint>(_e23) + as_type<uint>(1));
        }
        loop_init = false;
        int _e8 = i_1;
        if (_e8 < 4) {
        } else {
            break;
        }
        {
            float _e11 = v;
            float _e12 = a_1;
            metal::float2 _e13 = p_3;
            float _e14 = valueNoise(_e13);
            v = _e11 + (_e12 * _e14);
            metal::float2 _e17 = p_3;
            p_3 = _e17 * 2.0;
            float _e20 = a_1;
            a_1 = _e20 * 0.5;
        }
    }
    float _e26 = v;
    return _e26;
}

int naga_f2i32(float value) {
    return static_cast<int>(metal::clamp(value, -2147483600.0, 2147483500.0));
}

metal::float3 background(
    metal::float2 uv_1,
    Params params
) {
    float aspect_1 = {};
    metal::float2 uvAspect = {};
    float t_2 = {};
    float value = 0.0;
    float iTime = {};
    metal::float3 baseCol = {};
    metal::float3 haloCol = metal::float3(0.5019608, 0.18039216, 0.32941177);
    metal::float3 hotCol = metal::float3(0.8862745, 0.5019608, 0.63529414);
    metal::float3 lineCol = metal::float3(0.8235294, 0.42352942, 0.57254905);
    metal::float2 lightAnchor = {};
    float lightDist = {};
    float haloRadius = {};
    float coreRadius = {};
    float lightInfluence = {};
    float lightCore = {};
    metal::float3 col = {};
    type_6 baseY_1 = {};
    type_6 amp_1 = {};
    type_6 freq_1 = {};
    type_6 phase_1 = {};
    type_6 rimDepth = {};
    type_6 rimBoost = {};
    int i_2 = 0;
    float h_1 = {};
    float eps = {};
    float hLeft = {};
    float hRight = {};
    metal::float2 normal = {};
    metal::float2 toLight = {};
    float facing = {};
    bool local = {};
    float ht = {};
    float haloFactor = {};
    float depthWeight = {};
    float gradMul = {};
    metal::float3 body = {};
    float lineFalloff = {};
    float lineWidth = {};
    float lineSoftEdge = {};
    float lineMask = {};
    float haze = {};
    metal::float3 hazeTint = {};
    type_8 basePos = {};
    type_9 radius_1 = {};
    type_8 phase_2 = {};
    type_9 weight = {};
    int i_3 = 0;
    metal::float2 offset = {};
    metal::float2 pos = {};
    float influence = {};
    float bgWave = {};
    float baseVariation = {};
    float band = {};
    int bandIndex = {};
    metal::float3 color = {};
    float vignette = {};
    aspect_1 = params.resolution.x / params.resolution.y;
    float _e8 = aspect_1;
    metal::float2 _e9 = toAspect(uv_1, _e8);
    uvAspect = _e9;
    t_2 = params.time;
    if (params.is_dark > 0.5) {
        float _e18 = t_2;
        iTime = _e18 * 0.001;
        baseCol = metal::mix(metal::float3(0.05490196, 0.02745098, 0.0627451), metal::float3(0.0), params.oled);
        float _e47 = aspect_1;
        metal::float2 _e48 = toAspect(params.mouse, _e47);
        lightAnchor = _e48;
        metal::float2 _e50 = uvAspect;
        metal::float2 _e51 = lightAnchor;
        lightDist = metal::distance(_e50, _e51);
        haloRadius = metal::mix(1.0, 0.5, params.oled);
        coreRadius = metal::mix(0.28, 0.18, params.oled);
        float _e64 = haloRadius;
        float _e65 = lightDist;
        lightInfluence = 1.0 - metal::smoothstep(0.0, _e64, _e65);
        float _e71 = lightInfluence;
        float _e72 = lightInfluence;
        lightInfluence = _e71 * _e72;
        float _e74 = coreRadius;
        float _e75 = lightDist;
        lightCore = 1.0 - metal::smoothstep(0.0, _e74, _e75);
        float _e81 = lightCore;
        float _e82 = lightCore;
        float _e84 = lightCore;
        lightCore = (_e81 * _e82) * _e84;
        metal::float3 _e86 = baseCol;
        col = _e86 * 0.45;
        baseY_1.inner[0] = 0.7;
        amp_1.inner[0] = 0.16;
        freq_1.inner[0] = 1.4;
        float _e103 = iTime;
        phase_1.inner[0] = 0.3 + (_e103 * 0.07);
        baseY_1.inner[1] = 0.4;
        amp_1.inner[1] = 0.07;
        freq_1.inner[1] = 3.6;
        float _e115 = iTime;
        phase_1.inner[1] = 1.7 - (_e115 * 0.11);
        baseY_1.inner[2] = 0.28;
        amp_1.inner[2] = 0.07;
        freq_1.inner[2] = 3.0;
        float _e127 = iTime;
        phase_1.inner[2] = 0.9 - (_e127 * 0.05);
        baseY_1.inner[3] = 0.17;
        amp_1.inner[3] = 0.05;
        freq_1.inner[3] = 4.6;
        float _e139 = iTime;
        phase_1.inner[3] = 4.2 + (_e139 * 0.13);
        rimDepth.inner[0] = 0.12;
        rimDepth.inner[1] = 0.07;
        rimDepth.inner[2] = 0.07;
        rimDepth.inner[3] = 0.06;
        rimBoost.inner[0] = 0.11;
        rimBoost.inner[1] = 0.06;
        rimBoost.inner[2] = 0.07;
        rimBoost.inner[3] = 0.08;
        uint2 loop_bound_1 = uint2(4294967295u);
        bool loop_init_1 = true;
        while(true) {
            if (metal::all(loop_bound_1 == uint2(0u))) { break; }
            loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
            if (!loop_init_1) {
                int _e395 = i_2;
                i_2 = as_type<int>(as_type<uint>(_e395) + as_type<uint>(1));
            }
            loop_init_1 = false;
            int _e162 = i_2;
            if (_e162 < 4) {
            } else {
                break;
            }
            {
                int _e166 = i_2;
                float _e168 = baseY_1.inner[_e166];
                int _e169 = i_2;
                float _e171 = amp_1.inner[_e169];
                int _e172 = i_2;
                float _e174 = freq_1.inner[_e172];
                int _e175 = i_2;
                float _e177 = phase_1.inner[_e175];
                float _e178 = layerHeight(uv_1.x, _e168, _e171, _e174, _e177);
                float _e180 = iTime;
                float _e181 = sharedWave(uv_1.x, _e180);
                h_1 = _e178 + _e181;
                eps = 0.001;
                float _e187 = eps;
                int _e189 = i_2;
                float _e191 = baseY_1.inner[_e189];
                int _e192 = i_2;
                float _e194 = amp_1.inner[_e192];
                int _e195 = i_2;
                float _e197 = freq_1.inner[_e195];
                int _e198 = i_2;
                float _e200 = phase_1.inner[_e198];
                float _e201 = layerHeight(uv_1.x - _e187, _e191, _e194, _e197, _e200);
                float _e203 = eps;
                float _e205 = iTime;
                float _e206 = sharedWave(uv_1.x - _e203, _e205);
                hLeft = _e201 + _e206;
                float _e210 = eps;
                int _e212 = i_2;
                float _e214 = baseY_1.inner[_e212];
                int _e215 = i_2;
                float _e217 = amp_1.inner[_e215];
                int _e218 = i_2;
                float _e220 = freq_1.inner[_e218];
                int _e221 = i_2;
                float _e223 = phase_1.inner[_e221];
                float _e224 = layerHeight(uv_1.x + _e210, _e214, _e217, _e220, _e223);
                float _e226 = eps;
                float _e228 = iTime;
                float _e229 = sharedWave(uv_1.x + _e226, _e228);
                hRight = _e224 + _e229;
                float _e232 = hRight;
                float _e233 = hLeft;
                float _e236 = eps;
                normal = metal::normalize(metal::float2(-((_e232 - _e233)) / (2.0 * _e236), 1.0));
                metal::float2 _e244 = lightAnchor;
                float _e246 = h_1;
                float _e248 = aspect_1;
                metal::float2 _e249 = toAspect(metal::float2(uv_1.x, _e246), _e248);
                toLight = metal::normalize(_e244 - _e249);
                metal::float2 _e253 = normal;
                metal::float2 _e254 = toLight;
                facing = metal::max(metal::dot(_e253, _e254), 0.0);
                float _e260 = h_1;
                if (uv_1.y >= _e260) {
                    float _e265 = h_1;
                    int _e266 = i_2;
                    float _e268 = rimDepth.inner[_e266];
                    local = uv_1.y < (_e265 + _e268);
                } else {
                    local = false;
                }
                bool _e272 = local;
                if (_e272) {
                    float _e274 = h_1;
                    int _e276 = i_2;
                    float _e278 = rimDepth.inner[_e276];
                    ht = 1.0 - metal::clamp((uv_1.y - _e274) / _e278, 0.0, 1.0);
                    float _e286 = ht;
                    float _e287 = ht;
                    float _e289 = ht;
                    ht = (_e286 * _e287) * _e289;
                    float _e291 = lightInfluence;
                    float _e294 = facing;
                    haloFactor = 0.02 + ((1.1 * _e291) * _e294);
                    metal::float3 _e299 = col;
                    metal::float3 _e300 = haloCol;
                    metal::float3 _e301 = hotCol;
                    float _e302 = lightCore;
                    int _e306 = i_2;
                    float _e308 = rimBoost.inner[_e306];
                    float _e309 = ht;
                    float _e311 = haloFactor;
                    col = _e299 + (metal::mix(_e300, _e301, _e302 * 0.6) * ((_e308 * _e309) * _e311));
                }
                float _e316 = h_1;
                if (uv_1.y < _e316) {
                    int _e318 = i_2;
                    depthWeight = 0.4 + (0.6 * (static_cast<float>(_e318) / 3.0));
                    float _e327 = h_1;
                    gradMul = 0.75 + (0.25 * metal::clamp((_e327 - uv_1.y) / 0.25, 0.0, 1.0));
                    metal::float3 _e340 = baseCol;
                    float _e341 = gradMul;
                    body = _e340 * _e341;
                    metal::float3 _e344 = body;
                    metal::float3 _e345 = haloCol;
                    float _e346 = lightInfluence;
                    float _e350 = depthWeight;
                    body = _e344 + ((((_e345 * _e346) * 0.08) * _e350) * (1.0 - params.oled));
                    metal::float3 _e357 = body;
                    col = _e357;
                }
                float _e358 = lightInfluence;
                float _e359 = facing;
                lineFalloff = _e358 * _e359;
                float _e362 = lineFalloff;
                float _e363 = lineFalloff;
                lineFalloff = _e362 * _e363;
                lineWidth = 0.35 / params.resolution.y;
                lineSoftEdge = 2.5 / params.resolution.y;
                float _e375 = lineWidth;
                float _e376 = lineWidth;
                float _e377 = lineSoftEdge;
                float _e380 = h_1;
                lineMask = 1.0 - metal::smoothstep(_e375, _e376 + _e377, metal::abs(uv_1.y - _e380));
                metal::float3 _e387 = col;
                metal::float3 _e388 = lineCol;
                float _e389 = lineMask;
                float _e390 = lineFalloff;
                col = metal::mix(_e387, _e388, (_e389 * _e390) * 0.38);
            }
        }
        float _e400 = iTime;
        float _e406 = fbm((uv_1 * 2.5) + metal::float2(_e400 * 0.02, 0.0));
        haze = _e406;
        metal::float3 _e408 = baseCol;
        metal::float3 _e411 = haloCol;
        float _e414 = lightInfluence;
        hazeTint = metal::mix(_e408 * 0.5, _e411 * 0.35, _e414 * 0.5);
        metal::float3 _e419 = col;
        metal::float3 _e420 = hazeTint;
        float _e421 = haze;
        col = _e419 + ((_e420 * _e421) * 0.05);
        metal::float3 _e426 = col;
        return _e426;
    }
    basePos.inner[0] = metal::float2(0.3, 0.3);
    radius_1.inner[0] = 0.35;
    phase_2.inner[0] = metal::float2(0.0, 0.5);
    weight.inner[0] = 1.0;
    basePos.inner[1] = metal::float2(0.75, 0.35);
    radius_1.inner[1] = 0.32;
    phase_2.inner[1] = metal::float2(1.0, 0.0);
    weight.inner[1] = 0.95;
    basePos.inner[2] = metal::float2(0.5, 0.75);
    radius_1.inner[2] = 0.34;
    phase_2.inner[2] = metal::float2(2.0, 1.5);
    weight.inner[2] = 1.0;
    basePos.inner[3] = metal::float2(0.18, 0.65);
    radius_1.inner[3] = 0.3;
    phase_2.inner[3] = metal::float2(0.5, 2.0);
    weight.inner[3] = 0.9;
    basePos.inner[4] = metal::float2(0.85, 0.8);
    radius_1.inner[4] = 0.32;
    phase_2.inner[4] = metal::float2(1.5, 0.3);
    weight.inner[4] = 0.9;
    basePos.inner[5] = metal::float2(0.12, 0.15);
    radius_1.inner[5] = 0.28;
    phase_2.inner[5] = metal::float2(2.2, 1.8);
    weight.inner[5] = 0.85;
    uint2 loop_bound_2 = uint2(4294967295u);
    bool loop_init_2 = true;
    while(true) {
        if (metal::all(loop_bound_2 == uint2(0u))) { break; }
        loop_bound_2 -= uint2(loop_bound_2.y == 0u, 1u);
        if (!loop_init_2) {
            int _e554 = i_3;
            i_3 = as_type<int>(as_type<uint>(_e554) + as_type<uint>(1));
        }
        loop_init_2 = false;
        int _e506 = i_3;
        if (_e506 < 6) {
        } else {
            break;
        }
        {
            float _e508 = t_2;
            int _e511 = i_3;
            float _e514 = phase_2.inner[_e511].x;
            float _e519 = t_2;
            int _e522 = i_3;
            float _e525 = phase_2.inner[_e522].y;
            offset = metal::float2(metal::sin((_e508 * 0.0003) + _e514) * 0.14, metal::cos((_e519 * 0.00025) + _e525) * 0.14);
            int _e532 = i_3;
            metal::float2 _e534 = basePos.inner[_e532];
            metal::float2 _e535 = offset;
            float _e537 = aspect_1;
            metal::float2 _e538 = toAspect(_e534 + _e535, _e537);
            pos = _e538;
            metal::float2 _e540 = uvAspect;
            metal::float2 _e541 = pos;
            int _e542 = i_3;
            float _e544 = radius_1.inner[_e542];
            float _e545 = blob(_e540, _e541, _e544);
            influence = _e545;
            float _e547 = value;
            float _e548 = influence;
            int _e549 = i_3;
            float _e551 = weight.inner[_e549];
            value = _e547 + (_e548 * _e551);
        }
    }
    float _e560 = t_2;
    bgWave = (metal::sin((uv_1.x * 2.5) + (_e560 * 0.00008)) * 0.5) + 0.5;
    float _e570 = bgWave;
    float _e574 = t_2;
    bgWave = _e570 * ((metal::sin((uv_1.y * 2.0) + (_e574 * 0.00006)) * 0.5) + 0.5);
    float _e584 = bgWave;
    baseVariation = _e584 * 0.4;
    float _e588 = value;
    float _e589 = baseVariation;
    float _e590 = value;
    value = metal::max(_e588, _e589 * (1.0 - (_e590 * 0.8)));
    float _e597 = value;
    value = metal::clamp(_e597, 0.0, 0.99);
    float _e601 = value;
    band = metal::floor(_e601 * params.num_bands) / params.num_bands;
    float _e608 = band;
    bandIndex = naga_f2i32(_e608 * params.num_bands);
    color = params.colors.inner[0].xyz;
    int _e617 = bandIndex;
    if (_e617 == 1) {
        color = params.colors.inner[1].xyz;
    } else {
        int _e623 = bandIndex;
        if (_e623 == 2) {
            color = params.colors.inner[2].xyz;
        } else {
            int _e629 = bandIndex;
            if (_e629 == 3) {
                color = params.colors.inner[3].xyz;
            } else {
                int _e635 = bandIndex;
                if (_e635 == 4) {
                    color = params.colors.inner[4].xyz;
                } else {
                    int _e641 = bandIndex;
                    if (_e641 == 5) {
                        color = params.colors.inner[5].xyz;
                    } else {
                        int _e647 = bandIndex;
                        if (_e647 == 6) {
                            color = params.colors.inner[6].xyz;
                        } else {
                            int _e653 = bandIndex;
                            if (_e653 == 7) {
                                color = params.colors.inner[7].xyz;
                            } else {
                                int _e659 = bandIndex;
                                if (_e659 >= 8) {
                                    color = params.colors.inner[7].xyz;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    vignette = 1.0 - metal::smoothstep(0.5, 1.5, metal::length(uv_1 - metal::float2(0.5)) * 1.3);
    metal::float3 _e677 = color;
    float _e678 = vignette;
    color = _e677 * (0.94 + (0.06 * _e678));
    metal::float3 _e684 = color;
    return _e684;
}

// SwiftUI supplies top-left point coordinates and a packed float-array palette.
// All calculations remain float until the final SwiftUI half4 return.
using namespace metal;
[[ stitchable ]] half4 yapBackground(float2 position, half4 currentColor,
    float2 size, float time, float2 mouse, float isDark, float oled, float numBands,
    device const float* colors, int colorCount) {
    Params p = {};
    p.time = time;
    p.resolution = size;
    p.mouse = mouse;
    p.is_dark = isDark;
    p.oled = oled;
    p.num_bands = numBands;
    for (int i = 0; i < min(8, min(int(numBands), colorCount / 3)); ++i) {
        p.colors.inner[i] = float4(colors[i * 3], colors[i * 3 + 1], colors[i * 3 + 2], 0.0);
    }
    float2 uv = float2(position.x / size.x, 1.0 - position.y / size.y);
    return half4(half3(background(uv, p)), 1.0h);
}
