#!/usr/bin/env python3
"""Build Yap's Rust libraries, host-generated bindings, and XcodeGen iOS app."""
import argparse
import json
import os
import plistlib
from pathlib import Path
import shlex
import subprocess
import tempfile

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
GENERATED = HERE / "Generated"
BUNDLE = "town.yap.ios"


def run(*args, **kwargs):
    print("+ " + shlex.join(map(str, args)), flush=True)
    return subprocess.run(list(map(str, args)), cwd=ROOT, check=True, **kwargs)


def build_rust(target, release):
    built = run("cargo", "rustc", "-p", "yap-ios-host", "--lib", "--locked",
                *(["--release"] if release else []), "--target", target,
                "--message-format=json-render-diagnostics", "--", "--print=native-static-libs",
                # Colors would wrap the native-static-libs note parsed below.
                env={**os.environ, "IPHONEOS_DEPLOYMENT_TARGET": "18.0", "CARGO_TERM_COLOR": "never"},
                stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    print(built.stderr, flush=True)
    artifacts = [json.loads(line) for line in built.stdout.splitlines() if line.startswith("{")]
    [archive] = [name for artifact in artifacts if artifact.get("reason") == "compiler-artifact"
                 and artifact["target"]["name"] == "yap_ios_host"
                 for name in artifact["filenames"] if name.endswith(".a")]
    [native] = [line.removeprefix("note: native-static-libs: ")
                for line in built.stderr.splitlines() if line.startswith("note: native-static-libs: ")]
    return archive, shlex.split(native)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    profile = parser.add_mutually_exclusive_group()
    profile.add_argument("--release", dest="release", action="store_true", default=True)
    profile.add_argument("--debug", dest="release", action="store_false")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--simulator", nargs="?", const="booted", metavar="UUID")
    mode.add_argument("--simulator-build-only", action="store_true")
    mode.add_argument("--device", metavar="UDID")
    mode.add_argument("--archive", action="store_true", help="Archive and export for App Store Connect; never upload")
    args = parser.parse_args()
    if args.archive and not args.release:
        parser.error("--archive requires --release")
    GENERATED.mkdir(parents=True, exist_ok=True)
    lines = ["// Generated by build.py; do not edit.", "SENTRY_DSN =", '#include? "../Local.xcconfig"']
    for sdk, target in [("iphoneos", "aarch64-apple-ios"), ("iphonesimulator", "aarch64-apple-ios-sim")]:
        archive, libraries = build_rust(target, args.release)
        flags = [f"-Wl,-force_load,{archive}", *libraries]
        lines.append(f"OTHER_LDFLAGS[sdk={sdk}*] = $(inherited) " + " ".join('"' + flag + '"' for flag in flags))
    run("cargo", "bridgerton", "swift", "--package", "yap-ios-host",
        *(["--release"] if args.release else []), "--locked", "--out-dir", GENERATED / "Bindings")
    (GENERATED / "Link.xcconfig").write_text("\n".join(lines) + "\n")
    run("xcodegen", "generate", "--spec", HERE / "project.yml")
    if args.archive:
        archive = HERE / "DerivedData/Yap.xcarchive"
        run("xcodebuild", "archive", "-project", HERE / "Yap.xcodeproj", "-scheme", "Yap",
            "-configuration", "Release", "-destination", "generic/platform=iOS",
            "-archivePath", archive, "-derivedDataPath", HERE / "DerivedData", "-allowProvisioningUpdates")
        options = GENERATED / "ExportOptions.plist"
        options.write_bytes(plistlib.dumps({"method": "app-store-connect", "teamID": "AF2CJ3G3ZU",
            "uploadSymbols": True, "destination": "export", "signingStyle": "automatic"}))
        run("xcodebuild", "-exportArchive", "-archivePath", archive,
            "-exportOptionsPlist", options, "-exportPath", HERE / "DerivedData/export", "-allowProvisioningUpdates")
        return
    if not (args.simulator or args.simulator_build_only or args.device):
        return
    simulator = args.simulator
    if simulator == "booted":
        devices = json.loads(run("xcrun", "simctl", "list", "devices", "booted", "--json",
                                 capture_output=True, text=True).stdout)
        booted = [d["udid"] for group in devices["devices"].values() for d in group if d["state"] == "Booted"]
        if len(booted) != 1:
            parser.error("Specify --simulator UUID when there is not exactly one booted simulator")
        [simulator] = booted
    device_udid = None
    if args.device:
        # CoreDevice UUIDs and hardware UDIDs identify the same phone, but
        # xcodebuild only accepts the latter. devicectl accepts either.
        with tempfile.TemporaryDirectory(prefix="yap-device-") as directory:
            details = Path(directory) / "details.json"
            run("xcrun", "devicectl", "device", "info", "details", "--device", args.device,
                "--json-output", details, stdout=subprocess.DEVNULL)
            device_udid = json.loads(details.read_text())["result"]["hardwareProperties"]["udid"]
    destination = (f"id={device_udid}" if args.device else
                   f"platform=iOS Simulator,id={simulator}" if simulator else "generic/platform=iOS Simulator")
    configuration = "Release" if args.release else "Debug"
    run("xcodebuild", "build", "-project", HERE / "Yap.xcodeproj", "-scheme", "Yap",
        "-configuration", configuration, "-destination", destination,
        "-derivedDataPath", HERE / "DerivedData",
        *(["-allowProvisioningUpdates", "-allowProvisioningDeviceRegistration"] if args.device else ["CODE_SIGNING_ALLOWED=YES", "CODE_SIGN_IDENTITY=-"]))
    sdk = "iphoneos" if args.device else "iphonesimulator"
    app = HERE / "DerivedData/Build/Products" / f"{configuration}-{sdk}/Yap.app"
    if args.device:
        run("xcrun", "devicectl", "device", "install", "app", "--device", args.device, app)
        run("xcrun", "devicectl", "device", "process", "launch", "--device", args.device, "--terminate-existing", BUNDLE)
    elif simulator:
        run("xcrun", "simctl", "install", simulator, app)
        run("xcrun", "simctl", "launch", "--terminate-running-process", simulator, BUNDLE)


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as error:
        if error.stdout:
            print(error.stdout)
        if error.stderr:
            print(error.stderr)
        raise
