[package]
name = "google-speech"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = "1"
log = { workspace = true }
tokio = { workspace = true, features = ["time"] }
base64 = "0.22"
audio-codec = { path = "../audio-codec" }
