[package]
name = "publish-packs"
version = "0.1.0"
edition = "2024"

[dependencies]
language-utils = { path = "../language-utils" }
tokio.workspace = true
reqwest = { workspace = true, features = ["stream"] }
xxhash-rust.workspace = true
memmap2 = "0.9.11"
rusty-s3 = "0.10.2"
clap = { version = "4.6.7", features = ["derive"] }

[dev-dependencies]
tempfile.workspace = true
